
# This file is used to configure your Supabase project.
# It determines your project settings and permissions.

project_id = "ihtqcwysnusiiacmiubw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Config for your webhook functions
[functions.handle_new_user]
verify_jwt = true
